name: GitHub Action Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: .github/**
  pull_request:
    branches: 
    - main
  schedule:
    - cron : '15 06 ? * 0'
  workflow_dispatch:
    inputs:
       env :
        description: env
        required: true
        default: Load-Test
        type: choice
        options:
          - Load-Test
          - Test
          - Prod
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Echo event triger
         run: echo "Trigered by ${{ github.event_name }}"
       - name: Echo branch name
         run: echo "Branch name= ${{ github.ref_name }}"
       - uses: actions/checkout@v3.3.0

       - name: List files in the repository
         run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
  test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: "${{ github.event_name == 'workflow_dispatch' }} "
    steps:
      - run: echo "testing..."

         
  
    
