name: GitHub Action Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: /.github/*
  pull_request:
    branches: 
    - main
  schedule:
    - cron : '15 06 ? * 0'
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
       - name: Echo event triger
         run: echo "Trigered by ${{ github.event }}"
  
    
